# Generated by Django 3.2.5 on 2022-02-14 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingperiod',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 2, 21, 9, 2, 46, 631844)),
        ),
    ]
